#!/usr/bin/env lua

require"macro"

table.insert(package.loaders, 2, macro.loader)

local args = { ... }

local next_is_lib

for _, arg in ipairs(args) do
  if next_is_lib then
    next_is_lib = false
    require(arg)
  elseif arg == "-l" then
    next_is_lib = true
  else
    local lib = string.match(arg, "^-l[ ]?(.+)$")
    if lib then
      require(lib)
    else
      macro.dofile(arg)
    end
  end
end
